### PR TITLE
[fix]proofread English translation

### LINKED ISSUE #165: 网站英文翻译微调

### PR DESCRIPTION
**Pull request by PapayaHUANG**
Checklist（清单）:
- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes #165

### CODE REVIEW

File: translation/en-US.ts [hunk 1]
```diff
@@ -11,34 +11,34 @@ export default {
...
   idea2app_scaffolding: 'idea2app Scaffolding',
   registration_period: 'Registration Period',
-  activity_period: 'Ativity Period',
+  activity_period: 'Activity Period',
   register_after: ({ distance, unit }: Record<'distance' | 'unit', string>) =>
     textJoin('Registration after', distance, unit),
-  enrolling: 'Enrolling',
-  competition_over: 'Activity finished',
+  enrolling: 'Accepting Applications',
+  competition_over: 'Activity ended',
```
Comment (TechQuery) [inline translation/en-US.ts:18]: 字段名与英文翻译一致（下同）

**Review by TechQuery — APPROVED** [review]
